spring.application.name: API-Gateway
jwt.secret_key: P9bRq8c3ZjTNz7XLM5vJHyWcS4dGQ5Ef

server.port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka
  instance.:
    preferIpAddress: true

spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/users/**
          filters:
            - StripPrefix=2
        - id: post-service
          uri: lb://POST-SERVICE
          predicates:
            - Path=/api/v1/posts/**
          filters:
            - StripPrefix=2
            - name: AuthenticationFilter
        - id: connection-service
          uri: lb://CONNECTION-SERVICE
          predicates:
            - Path=/api/v1/connections/**
          filters:
            - StripPrefix=2
            - name: AuthenticationFilter
